# Generated by Django 2.2.27 on 2022-04-12 09:09

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imagemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='new_image%y%m%d')),
                ('image_b64', models.TextField(blank=True)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
