# Generated by Django 2.2.27 on 2022-04-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decimalmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField()),
                ('digits', models.IntegerField()),
                ('decimal_value', models.FloatField()),
            ],
        ),
    ]
