# Generated by Django 4.0.3 on 2022-04-06 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='nextform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_no', models.IntegerField()),
                ('password', models.IntegerField(null=True)),
                ('first_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='onetomany.main')),
            ],
        ),
    ]
