# Generated by Django 4.1.5 on 2023-01-08 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=70)),
                ('Password', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='main2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('second_name', models.CharField(max_length=70)),
                ('DOB', models.DateField()),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oto.main1')),
            ],
        ),
    ]
