# Generated by Django 2.2.27 on 2022-04-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_currency', '0003_remove_currency_symbol_datetime_currency_symbol_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_symbol',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
