# Generated by Django 2.2.27 on 2022-04-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgtobin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imagemodel',
        ),
    ]
