# Generated by Django 4.0.3 on 2022-04-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob_to_age', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dobtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='dob',
        ),
    ]
