# Generated by Django 2.2.27 on 2022-04-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob_to_age', '0002_dobtable_delete_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dobtable',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
