# Generated by Django 4.0.3 on 2022-04-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_validate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='validation',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
