# Generated by Django 2.2.27 on 2022-04-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_validate', '0002_alter_validation_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
