# Generated by Django 4.0.3 on 2022-04-07 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='first_name must string and should not be less than 3 and greater than 12', regex='^(?=.{3,12}$)(?![_.])(?!.*[_.]{2})[a-zA-Z]+(?<![_.])$')])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='last_name must string and should not be less than 3 and greater than 12', regex='^(?=.{3,12}$)(?![_.])(?!.*[_.]{2})[a-zA-Z]+(?<![_.])$')])),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='password must contain 8 letters and a captITAL letter and a special character ', regex='^.*(?=.{8,})(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=]).*$')])),
            ],
        ),
    ]
