# Generated by Django 2.2.27 on 2022-04-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='barmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('product_code', models.CharField(max_length=25)),
                ('pack_code', models.CharField(max_length=25)),
                ('bar_code', models.BinaryField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='barreaddb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_field', models.ImageField(upload_to='')),
            ],
        ),
    ]
