# Generated by Django 2.2.27 on 2022-04-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decimalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decimalmodel',
            name='decimal_value',
            field=models.CharField(max_length=100),
        ),
    ]
