# Generated by Django 4.0.6 on 2022-08-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=255)),
                ('password', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
    ]
