# Generated by Django 4.1.7 on 2023-03-22 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('EmpId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100)),
                ('PhoneNo', models.CharField(max_length=10)),
                ('AddressDetails', models.TextField()),
                ('HouseNo', models.CharField(max_length=200)),
                ('Street', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Photo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workExperience', models.CharField(max_length=1000)),
                ('CompanyName', models.CharField(max_length=200)),
                ('FromDate', models.DateField()),
                ('ToDate', models.DateField(max_length=200)),
                ('CompanyAddress', models.CharField(max_length=200)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workExperience', to='EmployeeCrud.employeemodel')),
            ],
        ),
        migrations.CreateModel(
            name='qualificationmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificationName', models.TextField(max_length=1000)),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('percentage', models.IntegerField()),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='EmployeeCrud.employeemodel')),
            ],
        ),
        migrations.CreateModel(
            name='projectmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('description', models.TextField(max_length=1000)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='EmployeeCrud.employeemodel')),
            ],
        ),
    ]
