# Generated by Django 4.0.3 on 2022-04-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_currency', '0002_currency_symbol_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency_symbol',
            name='datetime',
        ),
        migrations.AddField(
            model_name='currency_symbol',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
